### ISSUE TITLE
Using SevSeg with shift register (74hc595 or similar)

### ISSUE THREAD

**Issue by samgozman** [DeanIsMe/SevSeg#47]
Just for the start - Thank you for this very useful lib!
I want to use your lib with shift register 74hc595. To do this, I would like to be able to access a function that returns a number/digit codes from **digitCodeMap**. For example: 
```
sevseg.getNumber(1847,2)
//will return {B00000110,B01111111,B10000000,B01100110,B00000111}
sevseg.getChars("a")
//will return {B01110111}
```
I will be very grateful! 🙏

**Comment by DeanIsMe** [comment]
You're welcome!
I don't plan on adding those functions to the library, because it is not intended to be used with a shift register.
However, you can edit your copy to get the functionality. I recommend using the setNumber and setChars functions as normal. But then, instead of calling refreshDisplay, get the digit codes from the digitCode[] variable.
If you edit SevSeg.h and move 'byte digitCodes[MAXNUMDIGITS];' to the 'public:' section, you will be able to access it directly from your program.
